//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking_Systm_ver1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD
    {
        public decimal s_no { get; set; }
        public Nullable<decimal> account_no { get; set; }
        public string fd_mode { get; set; }
        public Nullable<decimal> rupees { get; set; }
        public Nullable<int> period { get; set; }
        public Nullable<decimal> intrest_rate { get; set; }
        public string maturity_date { get; set; }
        public Nullable<decimal> maturity_amount { get; set; }
        public string start_date { get; set; }
    
        public virtual user_account user_account { get; set; }
    }
}
