//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking_Systm_ver1._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bank_DatabaseEntities2 : DbContext
    {
        public Bank_DatabaseEntities2()
            : base("name=Bank_DatabaseEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_Table> admin_Table { get; set; }
        public virtual DbSet<debit> debits { get; set; }
        public virtual DbSet<deposit> deposits { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<FD> FDs { get; set; }
        public virtual DbSet<transfer> transfers { get; set; }
        public virtual DbSet<user_account> user_account { get; set; }
        public virtual DbSet<user_table> user_table { get; set; }
    }
}
