//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking_Systm_ver1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class transfer
    {
        public decimal s_no { get; set; }
        public string transfer_date { get; set; }
        public Nullable<decimal> account_no { get; set; }
        public string name { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<decimal> transfer_to { get; set; }
    
        public virtual user_account user_account { get; set; }
    }
}
