//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking_Systm_ver1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_account()
        {
            this.debits = new HashSet<debit>();
            this.deposits = new HashSet<deposit>();
            this.FDs = new HashSet<FD>();
            this.transfers = new HashSet<transfer>();
        }
    
        public decimal account_no { get; set; }
        public string name { get; set; }
        public string dob { get; set; }
        public Nullable<decimal> phone_no { get; set; }
        public string address { get; set; }
        public string district { get; set; }
        public string state { get; set; }
        public byte[] picture { get; set; }
        public string gender { get; set; }
        public string martial_status { get; set; }
        public string mother_name { get; set; }
        public string father_name { get; set; }
        public string registration_date { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<decimal> cnic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<debit> debits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deposit> deposits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FD> FDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transfer> transfers { get; set; }
    }
}
